#pragma once

enum OBJ_TYPE
{
	TYPE_PLAYER, TYPE_ENTITY, TYPE_MONSTER, TYPE_UI, TYPE_END
};

enum OBJ_STATE
{
	STATE_ALIVE, STATE_DEAD, STATE_IDLE, STATE_RUN, STATE_FIGHT, STATE_WORK, STATE_END
};

enum SCENE_TYPE
{
	SCENE_TITLE, SCENE_EDIT, SCENE_STAGE, SCENE_END
};