#pragma once

//ObjMgr에서 객체들을 관리할 때 OBJ_TYPE에서 따라 분류하여 관리한다.
enum OBJ_TYPE
{
	TYPE_BACKGROUND, TYPE_PLAYER, TYPE_ENTITY, TYPE_MONSTER, TYPE_UI, TYPE_END
};

enum OBJ_DIRECTION
{
	DIR_UP, DIR_UP_RIGHT, DIR_RIGHT, DIR_RIGHT_DOWN,
	DIR_DOWN, DIR_DOWN_LEFT, DIR_LEFT, DIR_LEFT_UP, DIR_END
};

enum OBJ_STATE
{
	STATE_IDLE, STATE_RUNNING, STATE_END
};

enum SCENE_TYPE
{
	SCENE_TITLE, SCENE_EDIT, SCENE_STAGE, SCENE_END
};